version: 2.1

orbs:
  android: circleci/android@1.0

jobs:
  build:
    executor:
      name: android/android
    steps:
      - checkout
      - run:
          name: Decrypt encrypted data
          command: |
            mkdir -p keys
            echo $KEYSTORE_DEBUG | base64 --decode >> keys/debug.keystore.gpg
            gpg --passphrase $GPG_PASSPHRASE --pinentry-mode loopback -o ./keys/debug.keystore -d ./keys/debug.keystore.gpg

            echo $KEYSTORE_RELEASE | base64 --decode >> keys/release.keystore.gpg
            gpg --passphrase $GPG_PASSPHRASE --pinentry-mode loopback -o ./keys/release.keystore -d ./keys/release.keystore.gpg

            echo $GOOGLE_SERVICES_JSON | base64 --decode >> app/google-services.json.gpg
            gpg --passphrase $GPG_PASSPHRASE --pinentry-mode loopback -o ./app/google-services.json -d ./app/google-services.json.gpg
      - run:
          name: Validate decrypted data
          command: |
            echo "3a15a7065ed4a62a747af2e3477b0a3e1940a7bc2946df638b902bcb186998e7 *keys/debug.keystore" | sha256sum --check
            echo "36a3bb8b7bda141b414c2df7fac7dcd09a2775769c561e562d2b43f7b246bfa5 *keys/release.keystore" | sha256sum --check
            echo "4c259d0e1b031108e3fa682353f7ca450827644422c736334f1b3f24cb10bc62 *app/google-services.json" | sha256sum --check
      - run:
          name: Run tests
          command: ./gradlew app:testDebugUnitTest
      - run:
          name: Assemble debug build
          command: ./gradlew app:assembleDebug
      - run:
          name: Assemble release build
          command: ./gradlew app:assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk

workflows:
  build:
    jobs:
      - build